//! `enclave-metadata` — field definitions, values, and the validation between them.
//!
//! Metadata is what turns a file store into a document system: the columns a library sorts by, the
//! facets search filters on, the properties a retention policy keys off. It is also the largest
//! surface of user-controlled data in the product that is neither file content nor a name.
//!
//! # The rule the whole crate follows: reject, never coerce
//!
//! A `NUMBER` field that accepts `"42"` has decided that a client sending strings is fine, and the
//! next client sends `"1e999"` or `"0x10"` or `""`. A `BOOLEAN` that accepts `"false"` will
//! eventually accept `"no"`, which is truthy in some language a caller is written in.
//!
//! The cost of rejecting is an error message. The cost of coercing is that the type in the field
//! definition stops describing the data, and every consumer downstream — the search index, a
//! filter, an export, a retention rule — has to re-derive what the column actually holds. See
//! [`validate`].
//!
//! # Validation is in two halves, and both are required
//!
//! [`validate::validate`] checks *shape*: type, bounds, format, choices. It is pure, total and
//! cheap, so it can run over every field of every row without touching a database.
//!
//! [`repo::validate_references`] checks *existence*, for the four types that name something —
//! `USER`, `GROUP`, `TAXONOMY`, `REFERENCE`. It needs a tenant-scoped transaction, which is exactly
//! why it is separate: a validator that took a connection would be one that ran inside every loop,
//! and a reference resolved without a tenant predicate would let a caller confirm that another
//! tenant's file exists.
//!
//! # `value_text` is generated by the database
//!
//! `docs/04-DATA-MODEL.md §10` calls it "a generated projection for filtering/sorting", and
//! `migrations/0009_metadata.sql` makes it a `GENERATED ALWAYS ... STORED` column rather than
//! something this crate writes. Filters and sorts read it, so a projection that could drift from
//! its source is a wrong answer to a query rather than a cosmetic defect — and it would drift the
//! first time anything wrote `value` without going through the writer that maintained it.
//!
//! # What this crate is not
//!
//! **It makes no authorization decision.** The policy chain is called from the handler, before a
//! domain service is reached (`plans/M1-CONTENT-CORE.md` D11). Whether a caller may set a field on
//! a resource is a question about the resource, answered before anything here runs.

pub mod error;
pub mod model;
pub mod repo;
pub mod validate;

pub use error::{FieldViolation, MetadataError, Result, ValidationOutcome};
pub use model::{FieldConfig, FieldScope, FieldType, MetadataField, ValueResourceKind};
pub use validate::{validate, DEFAULT_MAX_JSON_BYTES, DEFAULT_MAX_JSON_DEPTH};
