[package]
name        = "enclave-information_barriers"
description = "Mandatory segmentation"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
enclave-core = { workspace = true }

[lints]
workspace = true
