#!/usr/bin/env node
/**
 * Lift the icon sprite out of the prototype into a React component.
 *
 * The prototype defines 38 `<symbol>`s and every screen references them with
 * `<use href="#name">`. Hand-copying them per feature would give six subtly
 * different chevrons; generating one sprite from the reference gives one, and
 * re-running this after a prototype change is a diff rather than an audit.
 *
 * Run: node tools/extract-sprite.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = 'design-system/enclave-client-prototype.html';
const TARGET = 'src/shared/ui/icon-sprite.tsx';

const html = readFileSync(SOURCE, 'utf8');
const symbols = [...html.matchAll(/<symbol id="([a-z-]+)"([^>]*)>([\s\S]*?)<\/symbol>/g)].map(
  ([, id, attrs, body]) => ({ id, attrs: attrs.trim(), body: body.trim() }),
);

if (symbols.length === 0) {
  console.error(`extract-sprite: no <symbol> found in ${SOURCE}. Refusing to write an empty sprite.`);
  process.exit(2);
}

/** SVG presentation attributes to JSX props. */
function toJsx(attrs) {
  return attrs
    .replace(/viewBox="([^"]*)"/g, 'viewBox="$1"')
    .replace(/stroke-width="([^"]*)"/g, 'strokeWidth="$1"')
    .replace(/stroke-linecap="([^"]*)"/g, 'strokeLinecap="$1"')
    .replace(/stroke-linejoin="([^"]*)"/g, 'strokeLinejoin="$1"')
    .replace(/fill-rule="([^"]*)"/g, 'fillRule="$1"')
    .replace(/clip-rule="([^"]*)"/g, 'clipRule="$1"');
}

function bodyToJsx(body) {
  return body
    .replace(/stroke-width=/g, 'strokeWidth=')
    .replace(/stroke-linecap=/g, 'strokeLinecap=')
    .replace(/stroke-linejoin=/g, 'strokeLinejoin=')
    .replace(/fill-rule=/g, 'fillRule=')
    .replace(/clip-rule=/g, 'clipRule=')
    .replace(/><\/(circle|path|rect|line|polyline|ellipse)>/g, ' />')
    .replace(/<(circle|path|rect|line|polyline|ellipse)([^>]*[^/])>/g, '<$1$2 />');
}

const ids = symbols.map((s) => s.id);

const file = `/* GENERATED by tools/extract-sprite.mjs from ${SOURCE}. Do not edit by hand.
 *
 * One sprite, mounted once at the application root, referenced everywhere with
 * <Icon name="…" />. The prototype does exactly this and it is the reason a
 * chevron is the same chevron on all six screens.
 *
 * Every icon here is decorative: it repeats something the surface already says
 * in text, so <Icon> is aria-hidden and carries no <title>. A <title> is a
 * user-facing string and those live in the catalog (CLAUDE.md rule 12). An icon
 * that is the ONLY label for a control does not become accessible by gaining a
 * title — the control gets an aria-label from the catalog instead.
 */

export const ICON_NAMES = [
${ids.map((id) => `  '${id}',`).join('\n')}
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/** Mount once, at the root. Hidden, and referenced by every <Icon>. */
export function IconSprite() {
  return (
    <svg aria-hidden="true" focusable="false" style={{ display: 'none' }}>
${symbols
  .map(
    ({ id, attrs, body }) =>
      `      <symbol id="i-${id}" ${toJsx(attrs)}>\n        ${bodyToJsx(body)}\n      </symbol>`,
  )
  .join('\n')}
    </svg>
  );
}

export interface IconProps {
  readonly name: IconName;
  /** Pixel size. The prototype uses 10, 11, 12, 14 and 16; nothing else. */
  readonly size?: 10 | 11 | 12 | 14 | 16 | 20 | 24;
  readonly className?: string;
  readonly style?: React.CSSProperties;
}

export function Icon({ name, size = 14, className, style }: IconProps) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      width={size}
      height={size}
      aria-hidden="true"
      focusable="false"
      style={{ flex: 'none', ...style }}
    >
      <use href={\`#i-\${name}\`} />
    </svg>
  );
}
`;

writeFileSync(TARGET, file);
console.log(`extract-sprite: ${symbols.length} icons -> ${TARGET}`);
