[package]
name        = "enclave-retention"
description = "Retention policies and schedules"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
enclave-core = { workspace = true }
enclave-db   = { workspace = true }

anyhow      = { workspace = true }
async-trait = { workspace = true }
chrono      = { workspace = true }
sqlx        = { workspace = true }
thiserror   = { workspace = true }

[dev-dependencies]
enclave-testing = { workspace = true }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
uuid  = { workspace = true }

[lints]
workspace = true
