[package]
name        = "enclave-authorization"
description = "RBAC, ACL resolution, inheritance, effective permissions"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
enclave-core = { workspace = true }
async-trait  = { workspace = true }
uuid         = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
