//! Enclave's shared vocabulary: identifiers, actors, request context, actions, policy decisions
//! and the canonical error type.
//!
//! # The dependency rule
//!
//! **`core` depends on nothing else in this workspace, and it never will.**
//! Dependencies point inward (`plans/M0-FOUNDATIONS.md` D1):
//!
//! ```text
//! api / worker / scheduler        binaries — compose everything
//!         ↓
//! domain crates                   files, sharing, dlp, search, …
//!         ↓
//! policy services                 authorization, conditional_access, dlp, …
//!         ↓
//! infrastructure                  db, events, audit
//!         ↓
//! core · config                   depend on nothing above
//! ```
//!
//! That is what lets `PolicyEngine` be callable from `api`, `worker` and `mcp` without a cycle.
//! The corollary is a rule about *this* crate specifically: if a type needs to move into `core` in
//! order to break a cycle, the boundary that produced the cycle is wrong. Raise it rather than
//! widening `core` — a `core` that accumulates domain logic becomes a second workspace that
//! everything must recompile and nobody can reason about.
//!
//! Concretely, `core` holds no I/O, no database driver, no HTTP framework and no policy *logic*.
//! It holds the vocabulary those layers speak to each other in.
//!
//! # What lives here
//!
//! | Module | Contents |
//! |---|---|
//! | [`id`] | Typed identifiers over UUIDv7, generated by one macro so they cannot diverge |
//! | [`actor`] | Who is calling: [`Actor`], [`ClientType`] |
//! | [`context`] | [`RequestContext`] and the evidence conditional access evaluates |
//! | [`action`] | What is being attempted: [`Action`], [`FileAction`], [`ResourceRef`] |
//! | [`policy`] | [`PolicyDecision`] and [`Obligations`] — both `#[must_use]` |
//! | [`error`] | [`Error`], [`ReasonCode`], [`Remediation`], [`Result`] |
//!
//! # Two things that are load-bearing rather than stylistic
//!
//! 1. [`PolicyDecision`] and [`Obligations`] are `#[must_use]`. An obligation the caller drops is
//!    a control that silently did not happen; making it a compiler diagnostic rather than a code
//!    review finding is design decision D2 and non-negotiable rule 8.
//! 2. [`Error::PolicyDenied`] can only carry a [`ReasonCode`] and a [`Remediation`], both closed
//!    enumerations. Internal policy reasoning is *not representable* in it, so "we will sanitize
//!    it before it reaches the client" is not a promise anyone has to keep.

/// Generates a fixed-vocabulary enum together with everything needed to move it across a wire.
///
/// The point is that `as_str`, `Display`, `FromStr` and both serde halves are derived from a
/// single list of `Variant => "WIRE_STRING"` pairs, so they cannot disagree. A hand-written
/// `FromStr` that has fallen one variant behind its `as_str` is exactly the sort of defect that
/// shows up as a mysterious deserialization failure in production.
///
/// Parsing accepts any ASCII case. The same vocabularies appear lowercase in JWT claims
/// (`"cli": "web"`) and uppercase in database `CHECK` constraints (`'WEB'`), and rejecting one
/// spelling of the other's value buys nothing. Serialization always emits the canonical form given
/// in the macro invocation.
macro_rules! wire_enum {
    (
        $(#[$meta:meta])*
        $vis:vis enum $name:ident {
            $( $(#[$vmeta:meta])* $variant:ident => $wire:literal ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        $vis enum $name {
            $( $(#[$vmeta])* $variant ),+
        }

        impl $name {
            /// The stable machine-readable form. Stable means: changing one of these strings is a
            /// breaking change to the API, to stored audit rows, and to every client parsing them.
            #[must_use]
            pub const fn as_str(&self) -> &'static str {
                match self {
                    $( Self::$variant => $wire ),+
                }
            }

            /// Every variant, in declaration order — for exhaustiveness checks in tests and for
            /// admin surfaces that enumerate the vocabulary instead of hard-coding it.
            #[must_use]
            pub const fn all() -> &'static [Self] {
                &[ $( Self::$variant ),+ ]
            }
        }

        impl ::core::fmt::Display for $name {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        impl ::core::str::FromStr for $name {
            type Err = $crate::error::UnknownVariant;

            fn from_str(s: &str) -> ::core::result::Result<Self, Self::Err> {
                match s {
                    $( $wire => return Ok(Self::$variant), )+
                    _ => {}
                }
                $( if s.eq_ignore_ascii_case($wire) { return Ok(Self::$variant); } )+
                Err($crate::error::UnknownVariant::new(stringify!($name), s))
            }
        }

        impl ::serde::Serialize for $name {
            fn serialize<S: ::serde::Serializer>(&self, s: S) -> ::core::result::Result<S::Ok, S::Error> {
                s.serialize_str(self.as_str())
            }
        }

        impl<'de> ::serde::Deserialize<'de> for $name {
            fn deserialize<D: ::serde::Deserializer<'de>>(
                d: D,
            ) -> ::core::result::Result<Self, D::Error> {
                // Routed through `FromStr` on purpose: serde and manual parsing must never accept
                // different sets of strings.
                let raw = <::std::string::String as ::serde::Deserialize>::deserialize(d)?;
                raw.parse().map_err(::serde::de::Error::custom)
            }
        }
    };
}

pub mod action;
pub mod actor;
pub mod context;
pub mod engine;
pub mod error;
pub mod id;
pub mod policy;

pub use action::{
    Action, AdminAction, ContainerAction, FileAction, ResourceKind, ResourceRef, ShareAction,
};
pub use actor::{Actor, ActorKind, ClientType};
pub use context::{
    AuthStrength, DeviceContext, DevicePosture, NetworkContext, RequestContext, ScopeSet,
};
pub use engine::{
    AuthorizationService, BarrierService, ClassificationService, ConditionalAccessService,
    DlpService, PolicyAuditSink, PolicyEngine, RetentionService, Stage, StageDecision,
    StageOutcome,
};
pub use error::{
    Dependency, Error, FieldError, QuotaKind, ReasonCode, Remediation, Result, UnknownVariant,
    ValidationCode,
};
pub use id::{
    ChunkId, DeviceId, FileId, GroupId, GuestId, IdParseError, LibraryId, McpClientId, RequestId,
    ServiceAccountId, SessionId, TenantId, UserId, VersionId, WorkspaceId,
};
pub use policy::{ClassificationRank, Obligation, Obligations, PolicyDecision};

/// Re-exported so that downstream crates can name the raw type at the few boundaries where an
/// untyped UUID is legitimate (audit rows, database columns) without each of them having to decide
/// which `uuid` version to depend on.
pub use uuid::Uuid;
